### ISSUE TITLE
Where is the file "pcap2sigs" that can be executed?

### ISSUE THREAD

**Issue by jingzbu** [jingconan/pcap2sigs#1]
The following sample command does not work:
`$ ./pcap2sigs ./dosattack.pcap 0.0083`

**Comment by jingconan** [comment]
Hi Jing Z,
   pcap2sigs is another tool. The repo for the tool is here https://github.com/hbhzwj/pcap2sigs
   After downloading it, you can run 

``` bash
make pcap2sigs
```

in the directory to get a binary.
Jing W

**Comment by jingzbu** [comment]
All set. Thanks.
